_target_: context_flux_no.models.multiphysics.HyperNeuralOperatorv2
num_spatial_dims: ${..data.num_spatial_dims}
in_channels: ${..data.channels}
in_timesteps: ${..training.context_length}
embedding_dim: 128
encoder_type: TRecViT
encoder_kwargs:
  grid_size: [128,128]
  patch_size: [8, 8]
  depth: 2
  temporal_block_width: 128
  num_heads: 8
  mlp_hidden_dim: 64
normal_stencil_halfwidths: [4,4]
transverse_stencil_halfwidth: 2
reconstructions_per_channel: 16
depth_target: 6
hidden_dim: 128
width_hyper: 128
blocks_hyper: 2
hypernet_init: bias-hyperinit
key:
  _target_: jax.random.PRNGKey
  seed: 0